create table users (
       id integer generated by default as identity primary key,
       first_name varchar(255),
       last_name varchar(255),
       email varchar(255)
);

create table vehicles (
      id integer generated by default as identity primary key,
      brand varchar(255),
      model varchar(255),
      production_year integer not null,
      vehicle_type varchar(255),
      drive_type varchar(255),
      price_per_day double precision not null,
      available boolean not null,
      image_url varchar(255),
      description varchar(1000)
);

create table reservations (
      id integer generated by default as identity primary key,
      user_id integer,
      vehicle_id integer,
      start_date date,
      end_date date,
      total_price double precision not null,
      status varchar(255),
      constraint fk_reservations_user
          foreign key (user_id) references users(id),
      constraint fk_reservations_vehicle
          foreign key (vehicle_id) references vehicles(id)
);

create table payments (
      id integer generated by default as identity primary key,
      reservation_id integer unique,
      amount double precision not null,
      currency varchar(255),
      status varchar(255),
      provider_transaction_id varchar(255),
      payment_url varchar(255),
      created_at timestamp,
      paid_at timestamp,
      constraint fk_payments_reservation
          foreign key (reservation_id) references reservations(id)
);
