# change this line if you use mysql also don't forget about dependencies in pom.xml file ~Wojtek
spring.datasource.url=jdbc:postgresql://localhost:5432/carrental

# set username & password to your db
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true