# Configuracion para Base de Datos H2 guardada w pliku backend/data/carrental.mv.db
spring.datasource.url=jdbc:h2:file:./data/carrental;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar consola H2 (accesible en /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Habilitar Flyway para cargar los datos iniciales
spring.flyway.enabled=true
